language: objective-c
osx_image: xcode9
xcode_project: SwiftStandardLibrary.xcodeproj

env:
  global:
  - PROJECT=SwiftStandardLibrary.xcodeproj
  - IOS_SCHEME="SwiftStandardLibrary iOS"
  - IOS_SDK=iphonesimulator
  - TVOS_SCHEME="SwiftStandardLibrary tvOS"
  - TVOS_SDK=appletvsimulator
  - WATCHOS_SCHEME="SwiftStandardLibrary watchOS"
  - WATCHOS_SDK=watchsimulator
  - MACOS_SCHEME="SwiftStandardLibrary macOS"
  - MACOS_SDK=macosx

  matrix:
  - DESTINATION="platform=macos,arch=x86_64" SCHEME="$MACOS_SCHEME" SDK="$MACOS_SDK" RUN_TESTS="NO"
  - DESTINATION="OS=9.3,name=iPhone 6" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES"
  - DESTINATION="OS=10.3.1,name=iPhone 7" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES"
  - DESTINATION="OS=11.0,name=iPhone 8" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES"
  - DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="$TVOS_SCHEME" SDK="$TVOS_SDK" RUN_TESTS="YES"
  - DESTINATION="OS=11.0,name=Apple TV 4K" SCHEME="$TVOS_SCHEME" SDK="$TVOS_SDK" RUN_TESTS="YES"
  - DESTINATION="OS=2.1,name=Apple Watch - 38mm" SCHEME="$WATCHOS_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"
  - DESTINATION="OS=3.2,name=Apple Watch Series 2 - 38mm" SCHEME="$WATCHOS_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"
  - DESTINATION="OS=4.0,name=Apple Watch Series 3 - 42mm" SCHEME="$WATCHOS_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"

script:
- set -o pipefail
- xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
- if [[ "$RUN_TESTS" == "YES" ]]; then xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c; fi
